[project]
name = "pong"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "gymnasium[atari]",
    "opencv-python",
    "pandas",
    "pettingzoo",
    "pygame",
    "seaborn",
    "stable-baselines3",
    "torch",
]

